### PR TITLE
build!: update cool-seq-tool + ga4gh.vrs versions

### LINKED ISSUE #408: Update cool-seq-tool version
Use >= 0.1.13 once [this](https://github.com/GenomicMedLab/cool-seq-tool/pull/149) PR gets merged

### PR DESCRIPTION
**Pull request by korikuzma**
close #408 

Notes:
* Updates cool-seq-tool + ga4gh.vrs versions. This mainly had to do with fixing inter-residue positions. cool-seq-tool previous versions returned 0-based coordinates. 
* Temporarily removes gnomad_vcf_to_protein, which will be added back in #529 
* Tests
  ~~* The gnomad_vcf_to_protein tests are failing. They pass in the [issue-362-2-alpha branch](https://github.com/cancervariants/variation-normalization/tree/issue-362-2-alpha) for #362 . This branch is essentially done, just needs some code cleanup and will make a PR in the morning.~~
  * Validator fixtures were updated because a query was incorrectly classified
  * The normalize test was removed because the query actually has a MANE select priority

### CODE REVIEW

**Review by jsstevenson — DISMISSED** [review]

**Comment by korikuzma** [comment]
I think I'm waiting for #529 to be approved before I merge this. This is because gnomad_vcf_to_protein work is broken in this, but #529 files it

**Comment by korikuzma** [comment]
Linting will be resolved in a separate PR

**Review by jsstevenson — APPROVED** [review]
lgtm

**Comment by jsstevenson** [comment]
> Linting will be resolved in a separate PR

enjoy

**Comment by korikuzma** [comment]
@jsstevenson I already regret assigning the issue to myself

**Pull request merged**
