### PR TITLE
build!: update depdency versions

### PR DESCRIPTION
**Pull request by korikuzma**
Addresses #408 for main

Notes:
* Updates pydantic (v2), ga4gh.vrs, ga4gh.vrsatile.pydantic, gene-normalizer, + cool-seq-tool versions
* `UTA_DB_URL` now set through cool-seq-tool environment variable 
* `QueryHandler` only accepts `gene_query_handler` parameter
* Import statements for `cool_seq_tool` updated to latest architecture changes

### CODE REVIEW

**Review by jsstevenson — DISMISSED** [review]
lgtm

**Comment by korikuzma** [comment]
Converting to a draft. We may end up closing. Might just need to pin depdencies for manuscript.

**Comment by korikuzma** [comment]
I'll probably re-open after manuscript release is made.

**Comment by korikuzma** [comment]
I'm going to close this since we don't actively maintain 1.x anymore. If someone raises an issue, we can re-open.

**Pull request closed without merging**
