### PR TITLE
analysis: civic + moa variant analysis

### LINKED ISSUE #287: Run analysis on CIViC + MOAlmanac data
Will use [REST API](https://normalize.cancervariants.org/variation/normalize) for this analysis. See what we can and can't normalize using SPDI, HGVS, + free text queries from these sources.

### PR DESCRIPTION
**Pull request by korikuzma**
close #287 

Focuses mainly on the variants and terms we support, don't support, and whether or not we can normalize. I will fix the dependencies in #406

### CODE REVIEW

**Comment by korikuzma** [comment]
@jsstevenson if you want to review this, you can. If you don't have time, no worries. Just lmk

**Comment by jsstevenson** [comment]
@korikuzma thoughts on dotenv? I've thought about adding it elsewhere

**Comment by korikuzma** [comment]
> @korikuzma thoughts on dotenv? I've thought about adding it elsewhere

I like it! Especially when we have to set more than one env var for a project.

**Review by wesleygoar — CHANGES_REQUESTED** [review]
Can we change the name of the all_queries file to be more reflective of what it actually is please? I know should_be_able_to_normalize_queries is kinda long but is a much more accurate description of what is in the file. Doesnt have to be that name but something that gets the point across.

**Comment by korikuzma** [comment]
> Can we change the name of the all_queries file to be more reflective of what it actually is please? I know should_be_able_to_normalize_queries is kinda long but is a much more accurate description of what is in the file. Doesnt have to be that name but something that gets the point across.

Sure, I'll change to `should_be_able_to_normalize_queries`

**Comment by wesleygoar** [comment]
Awesome. Everything else looked great @korikuzma!

**Pull request merged**
