### PR TITLE
analysis: add notebook for CIViC + MOA evidence analysis 

### LINKED ISSUE #405: Identify amount of evidence associated to variant categories
The variant categories found in #287

### PR DESCRIPTION
**Pull request by anastasiasmith1221**
close #405

### CODE REVIEW

**Comment by wesleygoar** [comment]
@anastasiasmith1221 Excellent work! A few comments.

1. "Percentage of all CIViC Varinat Items" In your last table Variant is spelled incorrectly and I think we could come up with better names for those columns to be more clear. Could you help me understand what is being represented in the column labeled as "Percentage of all CIViC Evidence Items" please?
2. Could I get some stats on percentages of data using the evidence status in each of your tables please? Similar to what @korikuzma did for me in her notebook.

**Comment by korikuzma** [comment]
@anastasiasmith1221 I removed my review for now. When you and @wesleygoar think it's in a good place for me to review, just re-request my review.

**Comment by korikuzma** [comment]
@anastasiasmith1221 you had:

```python
normalized_queries_df = normalized_queries_df.drop_duplicates(subset=["variant_id"])
normalized_variant_id_list = list(normalized_queries_df["variant_id"])

total_number_normalized_variants = len(set(normalized_variant_id_list))
fraction_normalized_variants = f"{total_number_normalized_variants} / {total_number_variants}"
f"Number of Normalized Variants in CIViC: {fraction_normalized_variants}"
```

but I think it can be changed to:

```python
normalized_queries_df = normalized_queries_df.drop_duplicates(subset=["variant_id"])
normalized_variant_id_list = list(normalized_queries_df["variant_id"])

total_number_normalized_variants = len(normalized_variant_id_list)
fraction_normalized_variants = f"{total_number_normalized_variants} / {total_number_variants}"
f"Number of Normalized Variants in CIViC: {fraction_normalized_variants}"
```

so not casting `normalized_variant_id_list` as a set, since you are already dropping `variant_id` duplicates in the first line.

**Comment by korikuzma** [comment]
Not sure what the rest of this sentence was supposed to be:

> Evidence items are linked to the molecular profiles associated with variant items. To pull evidence IDs, we need to use molecular profiles. For more information on the structure of a variant item

**Comment by korikuzma** [comment]
Moved this over to the manuscript repo

**Pull request closed without merging**
